changelog:
  categories:
    - title: 🎁 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - fix
    - title: 🔧 Fixes
      labels:
        - fix
    - title: 📦 Dependencies
      labels:
        - dependencies
